---
repos:
  ccx-upgrades-inference:
    url: https://github.com/RedHatInsights/ccx-upgrades-inference
    default_branch: main
    source: github
  ccx-upgrades-data-eng:
    url: https://github.com/RedHatInsights/ccx-upgrades-data-eng
    default_branch: main
    source: github
  ccx-load-test:
    url: git@gitlab.cee.redhat.com:ccx/ccx-load-test
    default_branch: main
    source: gitlab
  parquet-factory:
    url: https://github.com/RedHatInsights/parquet-factory
    default_branch: main
    source: github
  ccx-data-pipeline:
    url: https://github.com/RedHatInsights/data-pipeline
    default_branch: main
    source: github
  ccx-insights-content-service:
    url: https://github.com/RedHatInsights/content-service
    default_branch: main
    source: github
  insights-results-aggregator:
    url: https://github.com/RedHatInsights/insights-results-aggregator
    default_branch: master
    source: github
  insights-results-aggregator-cleaner:
    url: https://github.com/RedHatInsights/insights-results-aggregator-cleaner
    default_branch: master
    source: github
  insights-results-aggregator-exporter:
    url: https://github.com/RedHatInsights/insights-results-aggregator-exporter
    default_branch: master
    source: github
  ccx-smart-proxy:
    url: https://github.com/RedHatInsights/insights-results-smart-proxy
    default_branch: master
    source: github
  ccx-notification-writer:
    url: https://github.com/RedHatInsights/ccx-notification-writer
    default_branch: master
    source: github
  ccx-notification-service:
    url: https://github.com/RedHatInsights/ccx-notification-service
    default_branch: master
    source: github
  io-gathering-service:
    url: https://github.com/RedHatInsights/insights-operator-gathering-conditions-service
    default_branch: main
    source: github
  ccx-insights-content-template-renderer:
    url: https://github.com/RedHatInsights/insights-content-template-renderer
    default_branch: master
    source: github
  insights-behavioral-spec:
    url: https://github.com/RedHatInsights/insights-behavioral-spec
    default_branch: main
    source: github
  obsint-mocks:
    url: https://github.com/RedHatInsights/obsint-mocks
    default_branch: main
    source: github
  ccx-messaging:
    url: https://github.com/RedHatInsights/insights-ccx-messaging
    default_branch: main
    source: github
